const lang = {
  en: {
    search: "Search",
    gpt_search_placeholder: "What would you like to watch today?",
    gpt_search_button_txt: "GPT Search",
    sign_out_button_txt: "Sign out",
    name_cannot_be_empty: "Name cannot be empty",
    user_already_exists:
      "User already exists. Try signing in or use another email to sign up.",
    unknown_error: "There was an unknown error. Please try again later",
    incorrect_username_password: "Incorrect username/ password.",
    sign_up: "Sign Up",
    sign_in: "Sign In",
    signing_in: "Signing in...",
    signing_up: "Signing up...",
    full_name: "Full Name",
    email: "Email",
    password: "Password",
    new_to_netflix: "New to Netflix?",
    sign_up_now: "Sign up Now!",
    sign_in_now: "Sign in Now!",
    already_registered: "Already registered?",
    invalid_email: "Invalid email. Enter valid email",
    invalid_password:
      "Invalid password. Password must be at least 8 characters long and include uppercase, lowercase, and a special character.",
    play: "Play",
    more_info: "More info",
    now_playing: "Now Playing",
    top_rated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
    horror: "Horror",
    action: "Action",
  },
  es: {
    search: "Buscar",
    gpt_search_placeholder: "¿Qué te gustaría ver hoy?",
    gpt_search_button_txt: "Búsqueda GPT",
    sign_out_button_txt: "Cerrar sesión",
    name_cannot_be_empty: "El nombre no puede estar vacío",
    user_already_exists:
      "El usuario ya existe. Intenta iniciar sesión o usa otro correo electrónico para registrarte.",
    unknown_error:
      "Hubo un error desconocido. Por favor, inténtalo de nuevo más tarde",
    incorrect_username_password: "Nombre de usuario/ contraseña incorrectos.",
    sign_up: "Registrarse",
    sign_in: "Iniciar sesión",
    signing_in: "Iniciando sesión...",
    signing_up: "Registrándose...",
    full_name: "Nombre completo",
    email: "Correo electrónico",
    password: "Contraseña",
    new_to_netflix: "¿Nuevo en Netflix?",
    sign_up_now: "¡Regístrate ahora!",
    sign_in_now: "¡Inicia sesión ahora!",
    already_registered: "¿Ya registrado?",
    invalid_email: "Correo electrónico inválido. Ingresa un correo válido",
    invalid_password:
      "Contraseña inválida. La contraseña debe tener al menos 8 caracteres e incluir mayúsculas, minúsculas y un carácter especial.",
    play: "Reproducir",
    more_info: "Más información",
    now_playing: "En cartelera",
    top_rated: "Mejor valoradas",
    popular: "Popular",
    upcoming: "Próximamente",
    horror: "Terror",
    action: "Acción",
  },
  hi: {
    search: "खोजें",
    gpt_search_placeholder: "आज आप क्या देखना चाहेंगे?",
    gpt_search_button_txt: "जीपीटी खोज",
    sign_out_button_txt: "साइन आउट करें",
    name_cannot_be_empty: "नाम खाली नहीं हो सकता",
    user_already_exists:
      "उपयोगकर्ता पहले से मौजूद है। साइन इन करने का प्रयास करें या साइन अप करने के लिए कोई और ईमेल उपयोग करें।",
    unknown_error: "एक अज्ञात त्रुटि हुई। कृपया बाद में पुनः प्रयास करें",
    incorrect_username_password: "गलत उपयोगकर्ता नाम/ पासवर्ड।",
    sign_up: "साइन अप करें",
    sign_in: "साइन इन करें",
    signing_in: "साइन इन हो रहा है...",
    signing_up: "साइन अप हो रहा है...",
    full_name: "पूरा नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    new_to_netflix: "नेटफ्लिक्स पर नए हैं?",
    sign_up_now: "अब साइन अप करें!",
    sign_in_now: "अब साइन इन करें!",
    already_registered: "पहले से पंजीकृत?",
    invalid_email: "अमान्य ईमेल। कृपया मान्य ईमेल दर्ज करें",
    invalid_password:
      "अमान्य पासवर्ड। पासवर्ड कम से कम 8 वर्ण लंबा होना चाहिए और इसमें अपरकेस, लोअरकेस और एक विशेष वर्ण शामिल होना चाहिए।",
    play: "चलाएं",
    more_info: "अधिक जानकारी",
    now_playing: "अब चल रहा है",
    top_rated: "शीर्ष रेटेड",
    popular: "लोकप्रिय",
    upcoming: "आगामी",
    horror: "हॉरर",
    action: "एक्शन",
  },
  kn: {
    search: "ಹುಡುಕಿ",
    gpt_search_placeholder: "ನೀವು ಇಂದು ಏನು ನೋಡಲು ಇಚ್ಛಿಸುತ್ತೀರಿ?",
    gpt_search_button_txt: "ಜಿಪಿಟಿ ಹುಡುಕು",
    sign_out_button_txt: "ಸೈನ್ ಔಟ್ ಮಾಡಿ",
    name_cannot_be_empty: "ಹೆಸರು ಖಾಲಿ ಇರಬಾರದು",
    user_already_exists:
      "ಬಳಕೆದಾರನು ಈಗಾಗಲೇ ಇದೆ. ಸೈನ್ ಇನ್ ಮಾಡಲು ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಸೈನ್ ಅಪ್ ಮಾಡಲು ಬೇರೆ ಇಮೇಲ್ ಬಳಸಿ.",
    unknown_error: "ಅಜ್ಞಾತ ದೋಷ ಸಂಭವಿಸಿದೆ. ದಯವಿಟ್ಟು ನಂತರ ಪುನಃ ಪ್ರಯತ್ನಿಸಿ",
    incorrect_username_password: "ತಪ್ಪಾದ ಬಳಕೆದಾರ ಹೆಸರು/ ಪಾಸ್‌ವರ್ಡ್.",
    sign_up: "ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    sign_in: "ಸೈನ್ ಇನ್ ಮಾಡಿ",
    signing_in: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...",
    signing_up: "ಸೈನ್ ಅಪ್ ಆಗುತ್ತಿದೆ...",
    full_name: "ಪೂರ್ಣ ಹೆಸರು",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    new_to_netflix: "ನೆಟ್ಫ್ಲಿಕ್ಸ್‌ನಲ್ಲಿ ಹೊಸದಾಗಿದ್ದೀರಾ?",
    sign_up_now: "ಈಗ ಸೈನ್ ಅಪ್ ಮಾಡಿ!",
    sign_in_now: "ಈಗ ಸೈನ್ ಇನ್ ಮಾಡಿ!",
    already_registered: "ಹಿಂದೆ ನೋಂದಾಯಿತಿದ್ದೀರಾ?",
    invalid_email: "ಅಮಾನ್ಯ ಇಮೇಲ್. ದಯವಿಟ್ಟು ಮಾನ್ಯ ಇಮೇಲ್ ನಮೂದಿಸಿ",
    invalid_password:
      "ಅಮಾನ್ಯ ಪಾಸ್‌ವರ್ಡ್. ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳ ಉದ್ದವಿರಬೇಕು ಮತ್ತು ದೊಡ್ಡ ಅಕ್ಷರ, ಸಣ್ಣ ಅಕ್ಷರ ಮತ್ತು ಒಂದು ವಿಶೇಷ ಅಕ್ಷರವನ್ನು ಒಳಗೊಂಡಿರಬೇಕು.",
    play: "ಆಡಿಸು",
    more_info: "ಹೆಚ್ಚಿನ ಮಾಹಿತಿ",
    now_playing: "ಈಗ ನಡೆಯುತ್ತಿದೆ",
    top_rated: "ಶ್ರೇಷ್ಟ ರೇಟಿಂಗ್",
    popular: "ಜನಪ್ರಿಯ",
    upcoming: "ಬರುವ",
    horror: "ಹಾರರ್",
    action: "ಆಕ್ಷನ್",
  },
};

export default lang;
