const lang = {
  en: {
    search: "Search",
    gpt_search_placeholder: "What would you like to watch today?",
    gpt_search_button_txt: "GPT Search",
    sign_out_button_txt: "Sign out",
    name_cannot_be_empty: "Name cannot be empty",
    user_already_exists:
      "User already exists. Try signing in or use another email to sign up.",
    unknown_error: "There was an unknown error. Please try again later",
    incorrect_username_password: "Incorrect username/ password.",
    sign_up: "Sign Up",
    sign_in: "Sign In",
    signing_in: "Signing in...",
    signing_up: "Signing up...",
    full_name: "Full Name",
    email: "Email",
    password: "Password",
    new_to_netflix: "New to Netflix?",
    sign_up_now: "Sign up Now!",
    sign_in_now: "Sign in Now!",
    already_registered: "Already registered?",
    invalid_email: "Invalid email. Enter valid email",
    invalid_password:
      "Invalid password. Password must be at least 8 characters long and include uppercase, lowercase, and a special character.",
    play: "Play",
    more_info: "More info",
    now_playing: "Now Playing",
    top_rated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
    horror: "Horror",
    action: "Action",
    homepage: "Homepage",
    searching: "Searching for movies...",
    clear: "Clear",
    loading: "Loading...",
    no_trailer_message: "Sorry, No trailer available for this movie",
    error_page:
      "Sorry, we can’t find that page. You’ll find loads to explore on the home page.",
    netflix_home: "NetflixGPT home",
    no_keywords_text: "No movies matched those keywords!",
  },
  es: {
    search: "Buscar",
    gpt_search_placeholder: "¿Qué te gustaría ver hoy?",
    gpt_search_button_txt: "Búsqueda GPT",
    sign_out_button_txt: "Cerrar sesión",
    name_cannot_be_empty: "El nombre no puede estar vacío",
    user_already_exists:
      "El usuario ya existe. Intenta iniciar sesión o usa otro correo electrónico para registrarte.",
    unknown_error:
      "Hubo un error desconocido. Por favor, inténtalo de nuevo más tarde",
    incorrect_username_password: "Nombre de usuario/ contraseña incorrectos.",
    sign_up: "Registrarse",
    sign_in: "Iniciar sesión",
    signing_in: "Iniciando sesión...",
    signing_up: "Registrándose...",
    full_name: "Nombre completo",
    email: "Correo electrónico",
    password: "Contraseña",
    new_to_netflix: "¿Nuevo en Netflix?",
    sign_up_now: "¡Regístrate ahora!",
    sign_in_now: "¡Inicia sesión ahora!",
    already_registered: "¿Ya registrado?",
    invalid_email: "Correo electrónico inválido. Ingresa un correo válido",
    invalid_password:
      "Contraseña inválida. La contraseña debe tener al menos 8 caracteres e incluir mayúsculas, minúsculas y un carácter especial.",
    play: "Reproducir",
    more_info: "Más información",
    now_playing: "En cartelera",
    top_rated: "Mejor valoradas",
    popular: "Popular",
    upcoming: "Próximamente",
    horror: "Terror",
    action: "Acción",
    homepage: "Página de inicio",
    searching: "Buscando películas...",
    clear: "claro",
    loading: "Cargando...",
    no_trailer_message:
      "Lo siento, no hay tráiler disponible para esta película",
    error_page:
      "Lo sentimos, no podemos encontrar esa página. Encontrarás mucho que explorar en la página principal.",
    netflix_home: "Inicio de NetflixGPT",
    no_keywords_text: "¡Ninguna película coincide con esas palabras clave!",
  },
  hi: {
    search: "खोजें",
    gpt_search_placeholder: "आज आप क्या देखना चाहेंगे?",
    gpt_search_button_txt: "जीपीटी खोज",
    sign_out_button_txt: "साइन आउट करें",
    name_cannot_be_empty: "नाम खाली नहीं हो सकता",
    user_already_exists:
      "उपयोगकर्ता पहले से मौजूद है। साइन इन करने का प्रयास करें या साइन अप करने के लिए कोई और ईमेल उपयोग करें।",
    unknown_error: "एक अज्ञात त्रुटि हुई। कृपया बाद में पुनः प्रयास करें",
    incorrect_username_password: "गलत उपयोगकर्ता नाम/ पासवर्ड।",
    sign_up: "साइन अप करें",
    sign_in: "साइन इन करें",
    signing_in: "साइन इन हो रहा है...",
    signing_up: "साइन अप हो रहा है...",
    full_name: "पूरा नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    new_to_netflix: "नेटफ्लिक्स पर नए हैं?",
    sign_up_now: "अब साइन अप करें!",
    sign_in_now: "अब साइन इन करें!",
    already_registered: "पहले से पंजीकृत?",
    invalid_email: "अमान्य ईमेल। कृपया मान्य ईमेल दर्ज करें",
    invalid_password:
      "अमान्य पासवर्ड। पासवर्ड कम से कम 8 वर्ण लंबा होना चाहिए और इसमें अपरकेस, लोअरकेस और एक विशेष वर्ण शामिल होना चाहिए।",
    play: "चलाएं",
    more_info: "अधिक जानकारी",
    now_playing: "अब चल रहा है",
    top_rated: "शीर्ष रेटेड",
    popular: "लोकप्रिय",
    upcoming: "आगामी",
    horror: "हॉरर",
    action: "एक्शन",
    homepage: "होमपेज",
    searching: "फिल्में खोजी जा रही हैं...",
    clear: "साफ करें",
    loading: "लोड हो रहा है...",
    no_trailer_message: "क्षमा करें, इस फिल्म का ट्रेलर उपलब्ध नहीं है",
    error_page:
      "क्षमा करें, हम उस पेज को नहीं ढूंढ सके। आपको होम पेज पर देखने और खोजने के लिए बहुत कुछ मिलेगा।",
    netflix_home: "नेटफ्लिक्सजीपीटी होम",
    no_keywords_text: "उन कीवर्ड्स से मेल खाती कोई फ़िल्म नहीं मिली!",
  },
  kn: {
    search: "ಹುಡುಕಿ",
    gpt_search_placeholder: "ನೀವು ಇಂದು ಏನು ನೋಡಲು ಇಚ್ಛಿಸುತ್ತೀರಿ?",
    gpt_search_button_txt: "ಜಿಪಿಟಿ ಹುಡುಕು",
    sign_out_button_txt: "ಸೈನ್ ಔಟ್ ಮಾಡಿ",
    name_cannot_be_empty: "ಹೆಸರು ಖಾಲಿ ಇರಬಾರದು",
    user_already_exists:
      "ಬಳಕೆದಾರನು ಈಗಾಗಲೇ ಇದೆ. ಸೈನ್ ಇನ್ ಮಾಡಲು ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಸೈನ್ ಅಪ್ ಮಾಡಲು ಬೇರೆ ಇಮೇಲ್ ಬಳಸಿ.",
    unknown_error: "ಅಜ್ಞಾತ ದೋಷ ಸಂಭವಿಸಿದೆ. ದಯವಿಟ್ಟು ನಂತರ ಪುನಃ ಪ್ರಯತ್ನಿಸಿ",
    incorrect_username_password: "ತಪ್ಪಾದ ಬಳಕೆದಾರ ಹೆಸರು/ ಪಾಸ್‌ವರ್ಡ್.",
    sign_up: "ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    sign_in: "ಸೈನ್ ಇನ್ ಮಾಡಿ",
    signing_in: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...",
    signing_up: "ಸೈನ್ ಅಪ್ ಆಗುತ್ತಿದೆ...",
    full_name: "ಪೂರ್ಣ ಹೆಸರು",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    new_to_netflix: "ನೆಟ್ಫ್ಲಿಕ್ಸ್‌ನಲ್ಲಿ ಹೊಸದಾಗಿದ್ದೀರಾ?",
    sign_up_now: "ಈಗ ಸೈನ್ ಅಪ್ ಮಾಡಿ!",
    sign_in_now: "ಈಗ ಸೈನ್ ಇನ್ ಮಾಡಿ!",
    already_registered: "ಹಿಂದೆ ನೋಂದಾಯಿತಿದ್ದೀರಾ?",
    invalid_email: "ಅಮಾನ್ಯ ಇಮೇಲ್. ದಯವಿಟ್ಟು ಮಾನ್ಯ ಇಮೇಲ್ ನಮೂದಿಸಿ",
    invalid_password:
      "ಅಮಾನ್ಯ ಪಾಸ್‌ವರ್ಡ್. ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳ ಉದ್ದವಿರಬೇಕು ಮತ್ತು ದೊಡ್ಡ ಅಕ್ಷರ, ಸಣ್ಣ ಅಕ್ಷರ ಮತ್ತು ಒಂದು ವಿಶೇಷ ಅಕ್ಷರವನ್ನು ಒಳಗೊಂಡಿರಬೇಕು.",
    play: "ಆಡಿಸು",
    more_info: "ಹೆಚ್ಚಿನ ಮಾಹಿತಿ",
    now_playing: "ಈಗ ನಡೆಯುತ್ತಿದೆ",
    top_rated: "ಶ್ರೇಷ್ಟ ರೇಟಿಂಗ್",
    popular: "ಜನಪ್ರಿಯ",
    upcoming: "ಬರುವ",
    horror: "ಹಾರರ್",
    action: "ಆಕ್ಷನ್",
    homepage: "ಹೋಮ್‌ಪೇಜ್",
    searching: "ಚಿತ್ರಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    clear: "ನಿಚ್ಚಳ",
    loading: "ಲೋಡಿಂಗ್...",
    no_trailer_message: "ಕ್ಷಮಿಸಿ, ಈ ಚಿತ್ರದ ಟ್ರೈಲರ್ ಲಭ್ಯವಿಲ್ಲ",
    error_page:
      "ಕ್ಷಮಿಸಿ, ನಾವು ಆ ಪುಟವನ್ನು ಕಂಡುಕೊಳ್ಳಲಿಲ್ಲ. ನೀವು ಮುಖಪುಟದಲ್ಲಿ ಅನ್ವೇಷಿಸಲು ಸಾಕಷ್ಟು ವಿಷಯಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಬಹುದು.",
    netflix_home: "ನೆಟ್‌ಫ್ಲಿಕ್ಸ್ಜಿಪಿಟಿ ಮುಖಪುಟ",
    no_keywords_text: "ಆ ಕೀವರ್ಡ್‌ಗಳಿಗೆ ಹೊಂದುವ ಯಾವುದೇ ಚಿತ್ರಗಳು ಕಂಡುಬಂದಿಲ್ಲ!",
  },
  tn: {
    search: "தேடல்",
    gpt_search_placeholder: "இன்று நீங்கள் என்ன பார்க்க விரும்புகிறீர்கள்?",
    gpt_search_button_txt: "ஜிபிடி தேடல்",
    sign_out_button_txt: "வெளியேறு",
    name_cannot_be_empty: "பெயர் காலியாக இருக்க முடியாது",
    user_already_exists:
      "பயனர் ஏற்கனவே உள்ளது. உள்நுழைய முயற்சிக்கவும் அல்லது பதிவு செய்ய வேறு மின்னஞ்சலைப் பயன்படுத்தவும்.",
    unknown_error:
      "அறியப்படாத பிழை ஏற்பட்டது. தயவுசெய்து பிறகு மீண்டும் முயற்சிக்கவும்",
    incorrect_username_password: "தவறான பயனர் பெயர்/ கடவுச்சொல்.",
    sign_up: "பதிவு செய்யவும்",
    sign_in: "உள்நுழையவும்",
    signing_in: "உள்நுழைகிறது...",
    signing_up: "பதிவு செய்கிறது...",
    full_name: "முழு பெயர்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    new_to_netflix: "நெட்ஃபிளிக்ஸில் புதியவரா?",
    sign_up_now: "இப்போது பதிவு செய்யவும்!",
    sign_in_now: "இப்போது உள்நுழைக!",
    already_registered: "முன்னதாக பதிவு செய்துள்ளீர்களா?",
    invalid_email: "தவறான மின்னஞ்சல். சரியான மின்னஞ்சலை உள்ளிடவும்",
    invalid_password:
      "தவறான கடவுச்சொல். கடவுச்சொல் குறைந்தது 8 எழுத்துகள் நீளமாக இருக்க வேண்டும் மற்றும் பெரிய எழுத்து, சிறிய எழுத்து மற்றும் ஒரு சிறப்பு எழுத்தை உள்ளடக்க வேண்டும்.",
    play: "பிளே",
    more_info: "மேலும் தகவல்",
    now_playing: "இப்போது ஒளிபரப்பில் உள்ளது",
    top_rated: "சிறந்த மதிப்பீடு",
    popular: "பிரபலமானது",
    upcoming: "வந்துவருகிறது",
    horror: "ஹாரர்",
    action: "செயல்",
    homepage: "முகப்பு பக்கம்",
    searching: "சினிமாக்களை தேடுகிறது...",
    clear: "சுத்தமான",
    loading: "ஏற்றுகிறது...",
    no_trailer_message: "மன்னிக்கவும், இந்த திரைப்படத்திற்கான டிரெய்லர் இல்லை",
    error_page:
      "மன்னிக்கவும், அந்தப் பக்கத்தை கண்டுபிடிக்க முடியவில்லை. முகப்புப் பக்கத்தில் நீங்கள் ஆராய பல உள்ளடக்கங்களை காணலாம்.",
    netflix_home: "நெட்ஃப்ளிக்ஸ்ஜிபிடி முகப்பு",
    no_keywords_text:
      "அந்த முக்கிய வார்த்தைகளுக்கு பொருந்தும் எந்த திரைப்படமும் இல்லை!",
  },
};

export default lang;
